name: dnametabarcoding
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.8.5
  - click=7.1.2
  - biopython=1.78
  - cutadapt=2.10
  - bioconductor-dada2=1.18.0
  - blast=2.10.1
  - pandas=1.1.3
  - r-taxizedb=0.2.2
  - bioconductor-phyloseq=1.34.0
